
spring.application.name=qloudprint-backend
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.maximum-pool-size=${DB_POOL_SIZE:3}
spring.sql.init.mode=never

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

server.port=${PORT:8080}

frontend.url=${FRONTEND_URL:http://localhost:5173}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}

platform.fee.percent=${PLATFORM_FEE_PERCENT:2}

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=${GMAIL_SMTP_USERNAME}
spring.mail.password=${GMAIL_SMTP_APP_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

app.mail.from=${GMAIL_SMTP_USERNAME}
